# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt -y install python3-venv pylint
        python3 -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install flake8 bandit[baseline]
        python -m pip install -U mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint, enforce static typing and check for bad practices
      run: |
        ./test.sh
