# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        wget https://downloads.python.org/pypy/pypy3.10-v7.3.16-linux64.tar.bz2
        tar xf pypy3.10-v7.3.16-linux64.tar.bz2
        which bash
        ./install-deps.sh
        source .venv/bin/activate
        if [ -f requirements.txt ]; then pypy -m pip install -r requirements.txt; fi
    - name: Lint, enforce static typing and check for bad practices
      run: |
        source .venv/bin/activate
        dmypy run -- *.py
        dmypy run -- */*.py
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --extend-exclude=".venv" --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --extend-exclude=".venv" --ignore=C901 --count --exit-zero --max-complexity=10 --max-line-length=319 --statistics
        bandit -r *.py
        bandit -r */*.py
        pylint --rcfile ./.pylintrc *.py
        pylint --rcfile ./.pylintrc */*.py

